# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lfcvtYIVf8j0bi03QMhRIVbi08F-4PRJ
"""

from flask import Flask

app = Flask(__name__)

@app.route('/')
def home():
    number_a = 15
    number_b = 5

# Adding the variables together
    total_sum = number_a + number_b

# Printing the result
   return f"The sum of {number_a} and {number_b} is {total_sum}."


if __name__ == '__main__':
    app.run()